import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openDb } from '../server/db.js';
import { createApp } from '../server/app.js';
import { buildZip } from '../server/zip.js';

export const PRUSA_GCODE = `; generated by PrusaSlicer 2.7.1 on 2026-01-02 at 10:00:00 UTC
G28
G1 X10 Y10
; filament used [g] = 3.42
; estimated printing time (normal mode) = 1h 2m 3s
; layer_height = 0.2
; temperature = 215
; bed_temperature = 60
; fill_density = 15%
; filament_type = PETG
; nozzle_diameter = 0.4
; perimeters = 3
; support_material = 0
; printer_model = MK4
`;

export const CURA_GCODE = `;FLAVOR:Marlin
;TIME:3725
;Filament used: 1.2m
;Layer height: 0.16
;Generated with Cura_SteamEngine 5.6.0
G28
`;

export const LBRN = `<?xml version="1.0"?>
<LightBurnProject AppVersion="1.4.00" DeviceName="Ortur LM3">
<CutSetting type="Cut"><index Value="0"/><name Value="C00"/><minPower Value="20"/><maxPower Value="65"/><speed Value="8"/><numPasses Value="2"/></CutSetting>
<CutSetting type="Scan"><index Value="1"/><name Value="C01"/><maxPower Value="30"/><speed Value="150"/><interval Value="0.1"/></CutSetting>
</LightBurnProject>`;

export const SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="100mm" height="50mm" viewBox="0 0 100 50">
<title>Coaster</title><path d="M0 0" stroke="#ff0000"/><path d="M1 1" style="stroke:#0000ff"/></svg>`;

export function stlBinary() {
  const b = Buffer.alloc(84 + 50);
  b.writeUInt32LE(1, 80);
  const verts = [[0, 0, 0], [10, 0, 0], [0, 20, 5]];
  verts.forEach((v, i) => v.forEach((n, j) => b.writeFloatLE(n, 84 + 12 + i * 12 + j * 4)));
  return b;
}

export function threeMf() {
  return buildZip([
    { name: '3D/3dmodel.model', data: Buffer.from('<model><metadata name="Title">Bracket</metadata><metadata name="Designer">Sam</metadata></model>') },
    { name: 'Metadata/Slic3r_PE.config', data: Buffer.from('; layer_height = 0.15\n; temperature = 230\n; filament_type = ABS\n') },
    { name: 'Metadata/thumbnail.png', data: Buffer.from('89504e470d0a1a0a', 'hex') },
  ]);
}

export async function startApp() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'vault-test-'));
  const db = openDb(':memory:');
  const server = createApp(db, { dataDir: dir, config: { brand: { name: 'Test' } } });
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const base = `http://127.0.0.1:${server.address().port}`;
  const api = async (method, url, body, headers = {}) => {
    const res = await fetch(base + url, {
      method, headers: { ...(body && !(body instanceof Buffer) ? { 'Content-Type': 'application/json' } : {}), ...headers },
      body: body instanceof Buffer ? body : body ? JSON.stringify(body) : undefined,
    });
    const type = res.headers.get('content-type') || '';
    const data = type.includes('json') ? await res.json() : Buffer.from(await res.arrayBuffer());
    return { status: res.status, data, res };
  };
  const close = () => { server.close(); fs.rmSync(dir, { recursive: true, force: true }); };
  return { api, base, dir, close };
}
